### ISSUE TITLE
proc-macro-hack is deprecated

### ISSUE THREAD

**Issue by langston-barrett** [tkaitchuck/constrandom#26]
The README says:

> Note: As of Rust 1.45 this crate is superseded by native support for #[proc_macro] in expression position. Only consider using this crate if you care about supporting compilers between 1.31 and 1.45.

Since [Rust 1.45 came out two years ago](https://blog.rust-lang.org/2020/07/16/Rust-1.45.0.html), it might be time to consider removing this dependency.

I noticed this because I wanted to use ASan on my code, and for some reason that causes the build of `proc-macro-hack` to fail.

**Comment by christopinka** [comment]
potentially related? Code coverage both with Tarpualin and intellij's grcov based instrumentation fails with 

error: could not compile `const-random` due to 2 previous errors
Jun 15 14:43:29.604 ERROR cargo_tarpaulin: Failed to compile tests!
error: ../target/debug/deps/libconst_random_macro-d64f87d46f5009b3.so: undefined symbol: __getrandom_custom
  --> /../.cargo/registry/src/github.com-1ecc6299db9ec823/const-random-0.1.15/src/lib.rs:16:9
   |
16 | pub use const_random_macro::const_random;
   |         ^^^^^^^^^^^^^^^^^^


Error: "Failed to compile tests!\nerror: /../git-test/di-apps/target/debug/deps/libconst_random_macro-d64f87d46f5009b3.so: undefined symbol: __getrandom_custom\n  --> /../.cargo/registry/src/github.com-1ecc6299db9ec823/const-random-0.1.15/src/lib.rs:16:9\n   |\n16 | pub use const_random_macro::const_random;\n   |         ^^^^^^^^^^^^^^^^^^\n\n"

**Comment by tkaitchuck** [comment]
Removed in https://github.com/tkaitchuck/constrandom/pull/27
